version: "3"

services:
  caurlshortener:
    image: caurlshortener:latest
    build: ./
    ports:
      - 8080:8080
    environment:
      - PASSWORD=MY_COOL_PASSWORD
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy

  mongodb:
    image: mongo:6.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password123
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password123
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password123
    depends_on:
      mongodb:
          condition: service_healthy
    ports:
      - 8081:8081
    healthcheck:
      test: wget --quiet --tries=3 --spider http://admin:password123@mongo-express:8081 || exit 1
      interval: 10s
      timeout: 10s
      retries: 10
    restart: unless-stopped

  redis:
    image: redis:7.2.1
    ports:
      - 6379:6379
    volumes:
      - redisdata:/root/redis
    environment:
      - REDIS_PASSWORD=password1
      - REDIS_DATABASES=16
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  mongodbdata:
  redisdata: